// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IContentfulTestFields {
  /** TestMessage */
  testMessage?: string | undefined;

  /** TestNumber */
  testNumber?: number | undefined;
}

/** Test */

export interface IContentfulTest extends Entry<IContentfulTestFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contentfulTest";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "contentfulTest";

export type IEntry = IContentfulTest;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
